name: Run ASV
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "20 * * * *"

env:
  ENV_FILE: environment.yml
  PANDAS_CI: 1
  BRANCH_NAME: test

permissions:
  contents: read

jobs:
  produce-asv-benchmarks:
    name: ASV Benchmarks
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}

    steps:
    - name: Checkout pandas
      uses: actions/checkout@v4
      with:
        repository: pandas-dev/pandas
        fetch-depth: 0

    - name: Checkout html
      uses: actions/checkout@v4
      with:
        sparse-checkout:  data/html
        fetch-depth: 0
        clean: false
        path:
          asv_bench/

    - name: Move html directory
      run: |
        mv asv_bench/data/html asv_bench/

    - name: Show files
      run: |
        ls -l 
        ls -l asv_bench/
        ls -l asv_bench/html

    - name: Set up Conda
      uses: ./.github/actions/setup-conda

    - name: Build pandas
      uses: ./.github/actions/build_pandas

    - name: Run ASV Benchmarks
      run: |
        cd asv_bench
        asv machine --machine=asvrunner --yes
        asv run --machine=asvrunner --python=same --set-commit-hash=$(git rev-parse HEAD) -b ^groupby.GroupByCythonAgg 
        asv publish

    - name: Save results directory as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: asv_bench/results/

    - name: Save html directory as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: html
        path: asv_bench/html/

  process-asv-benchmarks:
    name: Process ASV Benchmarks
    needs: produce-asv-benchmarks
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade build dependencies
        run: pip install -U pip

      - name: Install dependencies
        run: pip install pandas pyarrow

      - name: Download results
        uses: actions/download-artifact@v4
        with:
          name: results

      - name: Download html
        uses: actions/download-artifact@v4
        with:
          name: html
          path: data/html

      - name: Show files
        run: ls -l

      - name: Show files 2
        run: ls -l asvrunner/

      - name: Show files 3
        run: ls -l data/

      - name: Show files 4
        run: ls -l data/html/

      - name: Process ASV results
        run: |
          python ci/process_results.py

      - name: Save parquet results as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: results.parquet
          path: data/results.parquet
          retention-days: 14

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Results
          branch: ${{ env.BRANCH_NAME }}
          file_pattern: 'data/results.parquet data/html'
