name: Run ASV
on:
#  pull_request:
#    branches:
#      - main
  schedule:
    - cron: "20 * * * *"
  workflow_dispatch:

env:
  ENV_FILE: environment.yml
  PANDAS_CI: 1
  # Results and other data are stored away from the main branch.
  # This keeps the main branch clean and allows us to clear out
  # objects / history after being built up for long periods of time.
  BRANCH_NAME: pandas_20240109

permissions:
  contents: read

jobs:
  asv:
    name: Run ASVs
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash -el {0}
    permissions:
      contents: write
      issues: write
    outputs:
      new_commit: ${{ steps.new-commit.outputs.new_commit }}
    steps:
      # In order to run pandas' actions, we have to checkout into the root directory.
      - name: Checkout pandas
        uses: actions/checkout@v4
        with:
          repository: pandas-dev/pandas
          fetch-depth: 0

      - name: Checkout asv-runner results branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}
          path: asv-runner/

      - name: Compare Commit SHAs
        id: new-commit
        run: |
          if [ "$(git rev-parse HEAD)" = "$(cat asv-runner/data/latest_sha.txt)" ]; then
            echo "new_commit=no"
            echo "new_commit=no" >> "$GITHUB_OUTPUT"
          else
            echo "new_commit=yes"
            echo "new_commit=yes" >> "$GITHUB_OUTPUT"
          fi
          echo "$(git rev-parse HEAD)" > asv-runner/data/latest_sha.txt

      # Prevent another job from kicking off and running on this commit
      - name: Update latest_sha.txt
        if: ${{ steps.new-commit.outputs.new_commit == 'yes' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update latest SHA
          branch: ${{ env.BRANCH_NAME }}
          repository: asv-runner
          file_pattern: 'data/latest_sha.txt'

      - name: Set up Conda
        if: ${{ steps.new-commit.outputs.new_commit == 'yes' }}
        uses: ./.github/actions/setup-conda

      - name: Build pandas
        if: ${{ steps.new-commit.outputs.new_commit == 'yes' }}
        uses: ./.github/actions/build_pandas

      - name: Run ASV Benchmarks
        if: ${{ steps.new-commit.outputs.new_commit == 'yes' }}
        run: |
          cd asv_bench
          asv machine --machine=asvrunner --yes
          asv run --machine=asvrunner --python=same --set-commit-hash=$(git rev-parse HEAD) --show-stderr

      - name: Update asv-runner branch
        # In case there was a push by another job.
        if: ${{ steps.new-commit.outputs.new_commit == 'yes' }}
        run: |
          cd asv-runner
          git fetch && git pull

      - name: Move results into asv-runner
        if: ${{ steps.new-commit.outputs.new_commit == 'yes' }}
        run: |
          mkdir -p asv-runner/data/results
          cp asv_bench/results/benchmarks.json asv-runner/data/results/
          cp asv_bench/results/asvrunner/machine.json asv-runner/data/results/asvrunner/
          cp asv_bench/results/asvrunner/$(git rev-parse HEAD)-existing*.json asv-runner/data/results/asvrunner/

      - name: Commit results to branch
        if: ${{ steps.new-commit.outputs.new_commit == 'yes' }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Results
          branch: ${{ env.BRANCH_NAME }}
          repository: asv-runner
          file_pattern: 'data/results/'
